<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Prism.Host</AssemblyName>
        <RootNamespace>Prism.Host</RootNamespace>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

</Project>
